version: "0.2"
# ignorepaths: []
# dictionarydefinitions: []
# dictionaries: []
# ignorewords: []
# import: []
words:
  - aliasgroup
  - collabora
  - configmap
  - daemonset
  - duplicati
  - dynmap
  - healthcheck
  - kubernetes
  - lancache
  - loolwsd
  - meshroom
  - minecraft
  - modelstore
  - modports
  - nextcloud
  - notebookbar
  - puid
  - rcon
  - serviceexpert
  - ssvnc
  - statefulset
  - subquestions
  - tccr
  - traefik
  - truecharts
  - allowtransparency
  - appname
  - backupname
  - bazarr
  - bugfixer's
  - cheatsheet
  - dockerized
  - eptgmk
  - gibibyte
  - gluster
  - healthchecks
  - hostpath
  - hyperconverged
  - hyperthread
  - iban
  - ipaddr
  - ixcert
  - jackett
  - jacobalberty
  - jailman
  - killswitch
  - kjeld
  - kube
  - kubeconfig
  - kubectl
  - lebbing
  - letsencrypt
  - lidarr
  - loadbalancer
  - metallb
  - milicpu
  - minecraft
  - minio
  - mountpoint
  - nobind
  - nodeport
  - nodeports
  - ornias
  - ovpn
  - pgid
  - photoprism
  - pihole
  - plex
  - preconfigured
  - proto
  - pvcname
  - pvcpath
  - quotum
  - radarr
  - ramdisk
  - reneg
  - resolv
  - sabnzbd
  - schouten
  - selfsigned
  - smallblock
  - sonarr
  - sonarrsabnzbd
  - subchart
  - sublist
  - subquestion
  - svcname
  - syncthing
  - targetport
  - truenas
  - truetool
  - unifi
  - valheim
  - vaultwarden
  - ixsystems
  - vdev
  - vm's
  - websecure
  - xsystems
  - zwavejs
