# Project Information
site_name: TrueCharts
site_description: 'Project Documentation for TrueCharts'
site_author: 'TrueCharts Team'
docs_dir: docs/
site_url: 'https://truecharts.org'

# Repository
repo_name: 'truecharts/apps'
repo_url: 'https://github.com/truecharts/apps'
edit_uri: ""

copyright: Copyright &copy; 2020 - 2021 The TrueCharts Project

extra:
    generator: false

theme:
  name: 'material'
  language: 'en'
  logo: _static/img/logo1024.png
  favicon: _static/img/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
  - navigation.tabs
  - navigation.tracking
  - navigation.instant
  - search.highlight
  - search.share
  - search.suggest
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - _static/custom.css

# Plugins
plugins:
  #- search
  - awesome-pages
  - mkdocs-video
  - minify:
      minify_html: true


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
